### ISSUE TITLE
Suggestion for new update

### ISSUE THREAD

**Issue by canbeyy1** [RyleiC/MagickaForgeV2#2]
hi can you add edit spells I want create new summon spellls or edit vanilla spells

**Comment by canbeyy1** [comment]
> hi can you add edit spells I want create new summon spellls or edit vanilla spells

**Comment by RyleiC** [comment]
Like Magicks? Right now that would require source-code modding- although a patcher tool might be possible in the future

**Comment by RyleiC** [comment]
If you wish, a tool like https://github.com/dnSpy/dnSpy can be used to modify that kind of stuff in the meantime if you have knowledge in c#

**Comment by canbeyy1** [comment]
I dont know how to using dnspy but thanks to answer my question
